### ISSUE TITLE
GPU: Implementation task breakdown

### ISSUE THREAD

**Issue by j0sh** [livepeer/lpms#107]

**Comment by ericxtang** [comment]
I think this is done right?  Is [this hackmd](https://hackmd.io/0aD0aZgWQH-gedNkUVGSeg) the output?

**Comment by j0sh** [comment]
This RP was the deliverable : https://docs.google.com/document/d/1fOkjn8Sac2TNoAkxuBS46PNQIye55IHWrT1xsW79Lcg/edit#heading=h.ai5i82eq8you
