### ISSUE TITLE
RTMP authentication support

### ISSUE THREAD

**Issue by parthibd** [livepeer/lpms#115]
I want to use lpms as a standalone live streaming server . I see that webhook support in go-livepeer  . It the webhook facility not available in lpms ?

**Comment by j0sh** [comment]
The webhook in go-livepeer is implemented on top of LPMS via the createStreamID callback. If you're integrating LPMS in your application, then that's where you'd put the webhook call. Using the LPMS code example, that can be done here:

https://github.com/livepeer/lpms/blob/b09256040c6645f6eb250e7575100942db81a1a1/cmd/example/simple/simple.go#L37-L40

For reference, this is how it's done in the go-livepeer client: https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver.go#L160

**Comment by parthibd** [comment]
Thank you so much for the guidance @j0sh . Let me give it a try :)
