### ISSUE TITLE
Question regarding dependency

### ISSUE THREAD

**Issue by parthibd** [livepeer/lpms#117]
It seems like ```https://github.com/nareix/joy4``` is no longer maintained . So it this a good idea to use this library in lpms  ?

**Comment by j0sh** [comment]
joy4 hasn't needed a lot of maintenance, although admittedly issues are starting to pop up now that we're testing with various RTMP sources. Do you know of another golang RTMP library that would be a good replacement?

**Comment by parthibd** [comment]
I think [this](https://github.com/gwuhaolin/livego) might be a good candidate. Seems maintained . I don't think we should be using ```joy4``` for too long . And again we are constrained by good go streaming server libraries .

**Comment by j0sh** [comment]
Do you know if interoperability is better with other RTMP implementations? See https://github.com/livepeer/product/issues/9

Also are we able to easily incorporate the LPMS handler / callback architecture with this server?

**Comment by parthibd** [comment]
I looked around the code but it seems ( I might be wrong ) the callback architectures that lpms currently uses is not present in that library .

**Comment by parthibd** [comment]
We can fork the repo and maintain it on our own instead of moving to another whole new library entirely .

**Comment by j0sh** [comment]
> We can fork the repo and maintain it on our own instead of moving to another whole new library entirely 

Yeah that's basically what we do here: https://github.com/livepeer/joy4
