### ISSUE TITLE
Return pixels processed in FFMpegSegmentTranscoder.Transcode()

### ISSUE THREAD

**Issue by yondonfu** [livepeer/lpms#124]
At the moment, transcoding of a segment is kicked off by calling:

```
func (t *FFMpegSegmentTranscoder) Transcode(fname string) ([][]byte, error)
```

In order to implement livepeer/go-livepeer#896, an orchestrator needs to know the # of pixels processed during transcoding. In the short term, we just need to know the # of output pixels (we can leave input pixel accounting for the future).

We can update the function to:

```
func (t *FFMpegSegmentTranscoder) Transcode(fname string) (res [][]byte, receipts []Receipt, err error)
```

where `receipts[i]` corresponds to `res[i]`. The function will return a receipt for each transcoded result that contains the # of pixels processed for the transcoded result (perhaps other data could be included in this receipt in the future as well?).

This will require a change to `ffmpeg.Transcode` as well.

**Comment by j0sh** [comment]
Note that that style of API is deprecated with GPU support. This is what we currently have in ffmpeg.go:

```
func Transcode2(input *TranscodeOptionsIn, ps []TranscodeOptions) error
```

So for our case, how about returning the following struct instead:

```
ffmpeg.go
type TranscodeResults struct {
  filename string // read and convert to []byte data upstream if necessary
  video_frames int64
  pixels int64
  audio_frames int64
  ... any other data ...
}
func Transcode3(input *TranscodeOptionsIn, ps []TranscodeOptions) (res[] TranscodeResults, err error)
```

That way when we add extra fields to the response, the signature for the transcoding function does not have to change.

Also we've been moving away from using the `transcoder` module in favor or just using the `ffmpeg` module directly, and not breaking existing API (we have `ffmpeg.Transcode` and `ffmpeg.Transcode2` already).

Unless there's some extra processing of the results that better goes outside the `ffmpeg` module, I think we can continue down this path. I suspect we can remove the `transcoder` module entirely after we remove usage of the old API in goclient.

**Comment by yondonfu** [comment]
I'm on board with using the `TranscodeResults` struct to hold metadata for the result. For this issue, we really only need the `pixels` field.

Do we need to include `filename` in `TranscodeResults` though? Wouldn't this be a duplicate since `ps[i].Oname` will already hold the output filename for the ith rendition?

**Comment by j0sh** [comment]
> For this issue, we really only need the pixels field.

Yep. The other fields were just an example. Although most of those are pretty easy to add (eg, we can't get pixels without also looking at frames)

> Do we need to include filename in TranscodeResults though?

Right now, we don't necessarily need it for the reason you mention. But it'd be a bit more robust to include it anyway, for a couple reasons:

* Results may not always be returned in-order (although they are now)
* Allows the caller to propagate the results outside the scope of the transcoding parameters. For example, I'd love to stop slurping up all the data into a `[]byte` immediately after transcoding, and just create `io.Reader` instances from the file as necessary.

**Comment by mkrufky** [comment]
@yondonfu  Do we want to return pixel counts (and frame counts) per rendition, or as a whole?
I have issued a PR dealing with the counting as a whole.   If it turns out that we need to know per rendition , then I will change it.
The PR #140 returns pixels counted along with video frames counted, how does that look to you?

**Comment by mkrufky** [comment]
Yondon has explained on the Streamflow Testnet Engineering planning call that although this will satisfy the requirements as-is, the code on his side is stubbed out to expect the data on a per-rendition basis. As there is no harm is providing the data on a per-rendition basis, and it can be made readily available here, we will proceed that way.

**Comment by yondonfu** [comment]
Some additional information about how the go-livepeer code currently expects the pixel count:

At the moment, an orchestrator will include the pixel count for each rendition in a [TranscodedSegmentData](https://github.com/livepeer/go-livepeer/blob/master/net/lp_rpc.proto#L130) message and each [TranscodeResult](https://github.com/livepeer/go-livepeer/blob/master/net/lp_rpc.proto#L150) message can contain N `TranscodedSegmentData` messages. The pixel count of each of these `TranscodedSegmentData` is populated in [ServeSegment](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L486), but the pixel count is always 0 right now because of [this line of code](https://github.com/livepeer/go-livepeer/blob/master/core/orchestrator.go#L486). Once LPMS returns the pixel count along with the actual transcoded data we can populate the `pixels` field for each `TranscodedSegmentData` message.
