### ISSUE TITLE
Segmenter does not deliver segments consistently

### ISSUE THREAD

**Issue by j0sh** [livepeer/lpms#128]
The current segmenter works by:

* Polling for the existence of the *next* segment as a signal the current one is complete
* Reading the corresponding playlist to extract the duration, polling if the playlist is not ready.
* Returning the segment bytes and duration to the app.

The minimum poll interval for both the segment and playlist monitors are 100ms, and they are run sequentially.

This approach has a number of issues.

* There is significant variability in when a segment is made available to the goclient. This is primarily due to the polling strategy; observe that repeated runs of 1-1 B/O will show drops in mostly identical places. Filesystem latency contributes a little bit; running the datadir out of tmpfs increases the success rate ~4%. For data from one run, see https://gist.github.com/j0sh/69d1efc93b06ede46d97de939294c0e8

* Segmenter acts on a finite window and removes older segments from disk beyond the window. This will lead to issues with VOD or videos coming in faster than realtime. The original intent was to prune files to minimize disk usage, but we will likely want to revisit persistence at some point for various reasons.

* Seems to have issues processing small segment sizes. https://github.com/livepeer/go-livepeer/issues/885

There are a couple possible solutions.

* Check whether filesystem monitoring (eg, inotify via fsnotify) would improve consistency of segment delivery.

* Implement a segmenter in-process within the goclient. This should also mitigate the need to drop the first few seconds of the stream to synchronize on a keyframe.

**Comment by j0sh** [comment]
Proposed approach for quickly verifying filesystem monitoring:

* Check for file closing of the expected segment the using [fsnotify](https://github.com/fsnotify/fsnotify) (or another library). In inotify this is [IN_CLOSE_WRITE](http://man7.org/linux/man-pages/man7/inotify.7.html) ; not sure what the equivalent is on other platforms such as macOS.
* Only needs to work for one stream at a time (although it should be straightforward to extend to multiple streams by watching a different folder per stream)
* Omit the duration from the returned segment (we currently don't use it. However, if this monitoring approach seems viable, we should add the duration back in, as it'll likely be useful later on for optimizing transcoder selection)
* Check results for 1-1 B/O on both Linux and macOS using the standard test stream `official_test_source_2s_keys_24pfs`.

Then we can evaluate whether to move forward with this approach as a general solution, or continue looking at other approaches.

**Comment by j0sh** [comment]
Two more possible approaches for addressing this issue:

* Hook into FFmpeg callback API, and call back to the goclient each time the `io_close`  callback is invoked https://github.com/FFmpeg/FFmpeg/blob/2045dd0050f1ef0df348e11bd44657c2475aa7c3/libavformat/avformat.h#L1928-L1932 . Would require handling both .ts and .m3u8 files.

* Post segments / manifests to a local HTTP endpoint on the goclient. It might be useful to modify FFmpeg to also incorporate the duration in a header.

**Comment by darkdarkdragon** [comment]
I've found main problem - it was buffering in `joy4` RTMP code both on stream-tester and in `go-livepeer` node.
After putting `self.bufw.Flush()` (flushing output buffer of RTMP stream) between [these](https://github.com/livepeer/joy4/blob/livepeer/format/rtmp/rtmp.go#L1022-L1023) lines - I was able to stream both `official_test_source_2s_keys_24pfs` and my synthetic test [file](https://storage.googleapis.com/lp_testharness_assets/output2-20.mp4) with small segments with 100% success rate (to one broadcaster with one orchestrator).

**Comment by darkdarkdragon** [comment]
> Post segments / manifests to a local HTTP endpoint on the goclient. It might be useful to modify FFmpeg to also incorporate the duration in a header.

Probably it would be good idea to change polling code to receive HTTP requests from FFmpeg anyway. 
In my tests, FFmpeg send manifests like this:
```
I0628 16:25:06.627183    4789 serv.go:32] PUT /e914051e.m3u8 HTTP/1.1
Host: localhost:8000
Transfer-Encoding: chunked
Connection: close
Accept: */*
Connection: close
Icy-Metadata: 1
User-Agent: Lavf/58.20.100

69
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:1.980000,
e914051e_0.ts

0
```
This removes need to poll filesystem and read manifest from it - with this request from FFmpeg we have both event about segment availability pushed to us and have segment duration.
Only one possible drawback - it will create another TCP connection on broadcaster. Though don't how much it is problem.
