### ISSUE TITLE
Feature Request: store to disk the source and transcoded content

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/lpms#157]
As a broadcaster, I would like Livepeer to record the source content broadcasted and the transcoded content.

Primary objective: to capture content locally, and not decentrally.

Secondary objective: to be able to re-stream the same source and transcoded content later without needing to re-transcode the source when broadcasting.

**Comment by j0sh** [comment]
Hey Chris, thanks for opening this ticket. LPMS can store things on disk already. What you're asking for seems like a feature that would be exposed via a higher-level integration, where disk retention can be configured. Can you recreate this ticket in the [go-livepeer](https://github.com/livepeer/go-livepeer) repo?
