### ISSUE TITLE
Benchmark AMD cards with FFmpeg CLI

### ISSUE THREAD

**Issue by j0sh** [livepeer/lpms#169]

**Comment by wohlner** [comment]
How is this being documented?

**Comment by wohlner** [comment]
Please also share anything reproducibles, like scripts used for benchmarking.

**Comment by wohlner** [comment]
@faeez-kadiri can you please link to the spreadsheet?

**Comment by faeez-kadiri** [comment]
https://docs.google.com/spreadsheets/d/1VgsIEMFrLqh0vCHhX_2do4dMrJWuzhOqZKRLxdKfO8Q/edit?ts=5e330394#gid=0
