### ISSUE TITLE
Processing non-supported codec leads to segfault with CUDA

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/lpms#185]
To reproduce:
1. Generate video file `ffmpeg -loglevel quiet -f lavfi -i color=white:s=16x16 -vframes 1  -metadata title='!' -metadata service_provider='!' -f mpegts segment.ts`
2. Try to transcode using Nvidia acceleration.

Observe segment violation at https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_scale_cuda.c#L259

This is because for `mpeg2video` codec our function `get_hw_pixfmt` not being called by `avcodec_open2` function, and so `hw_frames_ctx` field is left uninitialised.

**Comment by j0sh** [comment]
Heh - mpeg2 isn't h264, so the naturally the cuda decoder isn't being initialized for that. What probably needs to happen here is to exit early if cuda is specified with a non-supported codec.

https://github.com/livepeer/lpms/blob/02ac425f2b6563a67189929a049dc489dbd936a9/ffmpeg/lpms_ffmpeg.c#L836-L847

Crash aside, is there still a problem with this fixed / minimized command ?

```
ffmpeg -f lavfi -i color=white:s=16x16 -vframes 1 -metadata title='!' -metadata service_provider='!' -c:v libx264 -f mpegts - | \
ffmpeg -f mpegts -i pipe:0 -c:v copy -bsf:v 'filter_units=pass_types=1-5' segment.ts
```
