### ISSUE TITLE
RTMPS,RTMPT,RTMPTE,RTMFP support?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [livepeer/lpms#193]
Hi,
is LPMS supports RTMPS,RTMPT,RTMPTE,RTMFP support? 

thanks

**Comment by j0sh** [comment]
Not directly, but there are some DIY options. RTMPS can be achieved by putting a TLS terminator in front of the node. I've done "RTMPT by proxy" with a separate process where incoming HTTP messages are unwrapped to a plain RTMP connection, and outgoing RTMP written to a hanging HTTP connection.

RTMPE / RTMFP require support within the implementation (joy4) and are not present as far as I know.

**Comment by ROBERT-MCDOWELL** [comment]
ok will try to implement it as soon as I can. thanks
