### ISSUE TITLE
Robust timestamp handling

### ISSUE THREAD

**Issue by jailuthra** [livepeer/lpms#199]
## Abstract

Currently the LPMS transcoder faces a lot of issues related to segment ordering and frame timestamps. This is a proposal to make the transcoding process more robust to failure when input segments are out of order or are missing a few frames.

## Motivation

Edge cases of out-of-order segments and missing frames happen often in real use of LPMS/Livepeer nodes. For example while retrying after a timeout/failure the Broadcaster would send a segment again which might have overlaping timestamps of a previously transcoded segment and thus fail. Or sometimes the client's mediaserver will drop some frames and thus skip over a chunk of timestamp, causing time drift in playback. (See #180 and #197 for more details)

## Proposed Solution

```
                                               FILTERGRAPH
                         +------------------------------------------------------+
                         |                                                      |
                         |      +------------+              +------------+      |
                         |      |            |              |            |      |
                         |      |            |              |            |      |
  +-----------+          |      |  SCALE     |              |  FPS       |      |         +-----------+
  |           |          |      |   filter   |              |   filter   |      |         |           |
  | decoded F +---------------->+            +------+------>+            +--------------->+ encoded F |
  |           |          |      |            |      ^       |            |      |         |           |
  +-----------+          |      |            |      |       |            |      |         +-----------+
                         |      |            |      |       |            |      |
     pts_in              |      |            |      |       |            |      |             pts_out
                         |      +------------+      |       +------------+      |    (2)
(non-monotonic &         |                          |                           |    (guess using pts_in & fps
 unreliable jumps)       +------------------------------------------------------+       to maintain same order)
                                                    |
                                                    |
                                                    |
                                                    +
                                           (1) dummy monotonic
                                                   pts
```

1. FPS filter expects monotonic increase in input frame's PTS. We cannot rely on the input to be monotonic thus:
    i. Set a dummy PTS before the frame is sent into filtergraph, that we manually increase monotonically.
    ii. OR use *SETPTS* filter in the filtergraph before FPS filter, which would do the same thing.

2. If the input had missing frames (jumps in PTS) or if we had used dummy PTS before for the fps filter - we would need to set the encoded frame's PTS manually to ensure correct order and timescaling after change in FPS.

### 1. Force monotonic PTS before FPS filter

We have two possible approaches here. Josh's WIP patch definitely works. Need to verify the `setpts` filter approach first, even though it looks cleaner and worked well with the ffmpeg cli.

**i. Josh's WIP patch**

Store the input PTS in the opaque field, and use a manual counter to set monotonic FPS before feeding the frame to the filtergraph.

```diff
@@ -1139,6 +1142,10 @@ int process_out(struct input_ctx *ictx, struct output_ctx *octx, AVCodecContext
     ret = init_video_filters(ictx, octx);
     if (ret < 0) return lpms_ERR_FILTERS;
   }
+  if (inf) {
+    inf->opaque = (void*)inf->pts;
+    filter->flush_offset += inf->pkt_duration;
+  }
   // Start filter flushing process if necessary
   if (!inf && !filter->flushed) {
     // Set input frame to the last frame
@@ -1148,14 +1155,15 @@ int process_out(struct input_ctx *ictx, struct output_ctx *octx, AVCodecContext
     AVFrame *frame = is_video ? ictx->last_frame_v : ictx->last_frame_a;
     filter->flush_offset += frame->pkt_duration;
     inf = frame;
-    inf->opaque = (void*)inf->pts; // value doesn't matter; just needs to be set
+    inf->opaque = NULL;
     is_flushing = 1;
   }
   if (inf) {
     // Apply the offset from filter flushing, then reset for the next output
-    inf->pts += filter->flush_offset;
+    int64_t old_pts = inf->pts;
+    inf->pts = filter->flush_offset;
     ret = av_buffersrc_write_frame(filter->src_ctx, inf);
-    inf->pts -= filter->flush_offset;
+    inf->pts = old_pts;
     if (ret < 0) proc_err("Error feeding the filtergraph");
   }
```

**ii. setpts Filter**

We can save some explicit calculation if we use the `setpts` [ffmpeg filter](https://ffmpeg.org/ffmpeg-filters.html#setpts_002c-asetpts) before the `fps` filter in our filtergraph.

### 2. Robust Output PTS calculation 

Josh's WIP patch already handles this case by using the input PTS and predicting the output PTS in the new timebase, while accomodating duplicated frames caused by the FPS filter:

```diff
@@ -1171,18 +1179,31 @@ int process_out(struct input_ctx *ictx, struct output_ctx *octx, AVCodecContext
       if (inf) return ret;
       frame = NULL;
     } else if (ret < 0) proc_err("Error consuming the filtergraph\n");
-    if (frame && frame->opaque) {
+    if (frame && !frame->opaque) {
       // opaque being set means it's a flush packet
       filter->flush_count++;
       // don't set flushed flag in case this is a flush from a previous segment
       if (is_flushing) filter->flushed = 1;
       frame->opaque = NULL; // reset just to be sure
       continue;
+    } else if (frame && frame->opaque) {
+      // TODO check with things like framerate pass through!
+      int64_t pts = (int64_t)frame->opaque;
+      pts = av_rescale_q_rnd(pts, ost->time_base, av_buffersink_get_time_base(filter->sink_ctx), AV_ROUND_NEAR_INF|AV_ROUND_PASS_MINMAX);
+      if (pts != filter->last_frame_pts) {
+        // Sometimes we have overlap between the calculated pts and what's
+        // received from the filter. Adjust so there's always a difference.
+        if (filter->last_frame_pts != AV_NOPTS_VALUE &&
+            filter->last_frame_pts + filter->frame_count >= pts) {
+          filter->frame_count = filter->last_frame_pts + filter->frame_count - pts;
+        } else filter->frame_count = 0;
+        filter->last_frame_pts = pts;
+      }
+
+      frame->pts = pts + filter->frame_count;
+      filter->frame_count++;
     }
 ```

Need to adapt this patch and ensure it works even when there are unexpected jumps in the input PTS.

## Testing Tasks and Considerations

* Extensive unit tests to handle the new codepaths and reproduce scenarios that caused issues on previous LPMS versions.
* A LOT of changes in the old testcases that depended heavily on the PTS ordering for verifying stuff and will now fail.

**Comment by j0sh** [comment]
Really glad that it appears we can solve two problems with one solution.

In the proposed solution, would we also be able to swap the `fps` and `scale` filters, since the DoS vector would presumably be resolved? https://github.com/livepeer/lpms/blob/e37613da13ad01dd9bf4272eab2cea160c8f2549/ffmpeg/ffmpeg.go#L225-L233

> A LOT of changes in the old testcases that depended heavily on the PTS ordering for verifying stuff and will now fail.

Presumably this would also fail with some cases that check against ffmpeg's CLI. Do you think we can find a knob within the CLI to match the new LPMS behavior? Or do we need to accept that we'll be drifting from the CLI baseline?

**Comment by jailuthra** [comment]
> In the proposed solution, would we also be able to swap the `fps` and `scale` filters, since the DoS vector would presumably be resolved?

Yep thats the plan! Forgot to mention it here.

> Presumably this would also fail with some cases that check against ffmpeg's CLI. Do you think we can find a knob within the CLI to match the new LPMS behavior? Or do we need to accept that we'll be drifting from the CLI baseline?

Yeah I believe we'd need to diverge from CLI now if the output timestamps differ wildly (or place bounds on difference instead of 1-on-1 compare). Can only try our best to keep it as close as possible.
