### ISSUE TITLE
ffmpeg/api_test: Fix commented-out unit tests

### ISSUE THREAD

**Issue by jailuthra** [livepeer/lpms#241]
We've got some commented-out unit tests that we should uncomment or move to a separate file with an `optional` build tag similar to what we've done for `nvidia` specific unit tests.
https://github.com/livepeer/lpms/blob/301900dd25100b0624104233c5ad644d9b023960/ffmpeg/api_test.go#L1297

**Comment by yondonfu** [comment]
Closed by #277
