### ISSUE TITLE
Benchmark impact of video signature filter on max session count on livepeer_bench

### ISSUE THREAD

**Issue by yondonfu** [livepeer/lpms#255]
We typically benchmarked a GPU using livepeer_bench by determining the maximum # of sessions (each session = decode + this [output encoding ladder](https://github.com/livepeer/go-livepeer/blob/master/cmd/livepeer_bench/transcodingOptions.json)) that can be supported with the "Real-Time Duration Ratio" metric reported by livepeer_bench <= 0.8 (meaning that the video was transcoded 20% faster than real-time). This benchmarking process gives a sense of not only how fast transcoding is, but also the maximum # of streams that could be transcoded using a GPU at an acceptable speed.

Inserting the video signature filter into the pipeline will introduce additional overhead in the following ways:

- The computation on the CPU for the signature
- The data copying between CPU & GPU since the filter currently can only be executed on a CPU

We already know the overhead from the computation on the CPU for the signature. But, we expect the data copying between CPU & GPU to create a bottleneck due the available PCIe throughput between the CPU & GPU. We can eventually address this by implementing a version of the filter that can run on the GPU. But, for now we should understand how the current use of the video signature filter impacts the max session count of a GPU.

We can do this by running a benchmark of a GPU first using livepeer_bench without the video signature filter. Then, we can do this by running a benchmark of the GPU using livepeer_bench with the video signature filter.

See the following resources for more information on benchmarking:

https://livepeer.org/docs/video-miners/how-to-guides/benchmarking
https://livepeer.org/docs/video-miners/how-to-guides/session-limits

**Comment by oscar-davids** [comment]
I used K80 single GPU. The max number of concurrent sessions is 3 on this GPU.  And we can know that signature calculation takes 100( 0.7247-0.6238) ms.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/oscar/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/oscar/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



No Sign   Mode | Sign Mode
-- | --
  |  
\| * Real-Time Duration Ratio *   \| 0.3117              1 | \| * Real-Time Duration Ratio * \| 0.3785             1
\| * Real-Time Duration Ratio *   \| 0.4376              2 | \| * Real-Time Duration Ratio * \| 0.5004             2
\| * Real-Time Duration Ratio *   \| 0.5707              3 | \| * Real-Time Duration Ratio * \| 0.625               3
\| * Real-Time Duration Ratio * \|   1.069                4 | \| * Real-Time Duration Ratio * \| 1.075               4
\| * Real-Time Duration Ratio * \|   1.326                5 | \| * Real-Time Duration Ratio * \| 1.332               5
\| * Real-Time Duration Ratio * \|   1.582                6 | \| * Real-Time Duration Ratio * \| 1.587               6
\| * Real-Time Duration Ratio * \|   1.83                  7 | \| * Real-Time Duration Ratio * \| 1.841               7
  |  
*------------------------------*---------------* | *------------------------------*---------------------*
\| Concurrent Sessions            \| 1             \| | \| Concurrent Sessions          \|   1                   \|
\| Total Segs Transcoded        \| 30            \| | \| Total Segs Transcoded        \|   30                  \|
\| Real-Time Segs Transcoded    \| 30            \| | \| Real-Time Segs Transcoded    \|   30                  \|
\| * Real-Time Segs Ratio *     \| 1             \| | \| * Real-Time Segs Ratio *     \|   1                   \|
\| Total Source Duration        \| 60s           \| | \| Total Source Duration        \|   60s                 \|
\| Total Transcoding Duration   \| 18.715307263s \| | \| Total Transcoding Duration   \|   21.741083952000004s \|
\| Seg Transcoding   Duration     \| 0.6238s       \| | \| Seg Transcoding Duration       \| 0.7247s             \|
\| * Real-Time Duration Ratio * \|   0.3119        \| | \| * Real-Time Duration Ratio * \| 0.3624              \|
*------------------------------*---------------* | *------------------------------*---------------------*
*------------------------------*--------------------* | *------------------------------*---------------------*
\| Concurrent Sessions          \| 2                  \| | \| Concurrent Sessions          \|   2                   \|
\| Total Segs Transcoded        \| 60                 \| | \| Total Segs Transcoded        \|   60                  \|
\| Real-Time Segs Transcoded    \| 60                 \| | \| Real-Time Segs Transcoded    \|   60                  \|
\| * Real-Time Segs Ratio *     \| 1                  \| | \| * Real-Time Segs Ratio *     \|   1                   \|
\| Total Source Duration        \| 120s               \| | \| Total Source Duration        \|   120s                \|
\| Total Transcoding Duration   \| 52.35916957099999s \| | \| Total Transcoding Duration   \|   60.226159882000005s \|
\| Seg Transcoding Duration     \| 0.8727s            \| | \| Seg Transcoding Duration     \|   1.004s              \|
\| * Real-Time Duration Ratio * \|   0.4363             \| | \| * Real-Time Duration Ratio * \| 0.5019              \|
*------------------------------*--------------------* | *------------------------------*---------------------*
*------------------------------*---------------------* | *------------------------------*---------------------*
\| Concurrent Sessions          \| 3                   \| | \| Concurrent Sessions          \|   3                   \|
\| Total Segs Transcoded        \| 90                  \| | \| Total Segs Transcoded        \|   90                  \|
\| Real-Time Segs Transcoded    \| 90                  \| | \| Real-Time Segs Transcoded    \|   90                  \|
\| * Real-Time Segs Ratio *     \| 1                   \| | \| * Real-Time Segs Ratio *     \|   1                   \|
\| Total Source Duration        \| 179.99999999999997s \| | \| Total Source Duration        \|   179.99999999999997s \|
\| Total Transcoding Duration   \| 103.04188569200004s \| | \| Total Transcoding Duration   \|   113.50746787399999s \|
\| Seg Transcoding Duration     \| 1.145s              \| | \| Seg Transcoding Duration     \|   1.261s              \|
\| * Real-Time Duration Ratio * \|   0.5725              \| | \| * Real-Time Duration Ratio * \| 0.6306              \|
*------------------------------*---------------------* | *------------------------------*---------------------*
*------------------------------*---------------------* | *------------------------------*----------------*
\| Concurrent Sessions          \| 4                   \| | \| Concurrent Sessions          \|   4              \|
\| Total Segs Transcoded        \| 120                 \| | \| Total Segs Transcoded        \|   120            \|
\| Real-Time Segs Transcoded    \| 20                  \| | \| Real-Time Segs Transcoded    \|   17             \|
\| * Real-Time Segs Ratio *     \| 0.1667              \| | \| * Real-Time Segs Ratio *     \|   0.1417         \|
\| Total Source Duration        \| 240s                \| | \| Total Source Duration        \|   240s           \|
\| Total Transcoding Duration   \| 256.35619638599997s \| | \| Total Transcoding Duration   \|   258.225729689s \|
\| Seg Transcoding Duration     \| 2.136s              \| | \| Seg Transcoding Duration     \|   2.152s         \|
\| * Real-Time Duration Ratio * \|   1.068               \| | \| * Real-Time Duration Ratio * \| 1.076          \|
*------------------------------*---------------------* | *------------------------------*----------------*



</body>

</html>

**Comment by yondonfu** [comment]
@oscar-davids will repeat this benchmark on a GPU with a greater base capacity (i.e. without video sig filter) to see what happens when there is more data being passed between the GPU and CPU when the video sig filter is used.

**Comment by oscar-davids** [comment]
I had benchmark on the VNO server with 2 x GTX 1080.
In the sign-off mode, maximum number of sessions was 34, there was an error(CUDA_ERROR_OUT_OF_MEMORY: out of memory) in more than 34 concurrent sessions.(signoffratio.log, signofffull.log)
Even when "Real-Time Duration Ratio" is smaller than 1.0, "Total Segs Transcoded" was not the same as "Real-Time Segs Transcoded", meaning transcoding is not stable since it implies some segments has not been transcoded successfully in time.

i.e Concurrent Sessions 20 in sign-off mode
*------------------------------*---------------------*
| Concurrent Sessions               | 20                  |
**| Total Segs Transcoded            | 600                |**
**| Real-Time Segs Transcoded    | 541                |**
| * Real-Time Segs Ratio *     | 0.9017              |
| Total Source Duration        | 1199.9999999999989s |
| Total Transcoding Duration   | 455.62089165399976s |
| Seg Transcoding Duration     | 0.7594s             |
| * Real-Time Duration Ratio * | 0.3797              |
*------------------------------*---------------------*  

Considering this, I think it is reasonable to say that the safe concurrent session Max is 16 for sign-on mode and 19 for sign-off mode.
One thing that is weird in the experiment and is worth noting is that in sign-mode, up to 40 max sessions run normally, but in sign-off mode, the error occurs in the 35th concurrent session.
[signofffull.log](https://github.com/livepeer/lpms/files/7006052/signofffull.log)
[signoffratio.log](https://github.com/livepeer/lpms/files/7006054/signoffratio.log)
[signonfull.log](https://github.com/livepeer/lpms/files/7006055/signonfull.log)
[signonratio.log](https://github.com/livepeer/lpms/files/7006056/signonratio.log)
