### ISSUE TITLE
Make FFmpeg Transcoder Asynchronous

### ISSUE THREAD

**Issue by ericxtang** [livepeer/lpms#27]
Transcoding tasks can take a while - we should make it async so the server can handle more requests.

**Comment by j0sh** [comment]
This doesn't seem to be an issue anymore; the [`Transcode`](https://github.com/livepeer/lpms/blob/0aae9a88834dd22253e00b98c3ed7d4c969793ed/transcoder/ffmpeg_segment_transcoder.go#L24) function can be put into its own goroutine by the caller as needed.
