### ISSUE TITLE
CompareSignatureByBuffer returns -1

### ISSUE THREAD

**Issue by leszko** [livepeer/lpms#272]
Related to https://github.com/livepeer/go-livepeer/issues/2095

On some environments the `C.lpms_compare_sign_bybuffer()` function returns `-1` for the following p-hashes.
```
version https://git-lfs.github.com/spec/v1
oid sha256:ad809c74a69f68a364c3b133d1f2cbf23fa04ea7d3fea9448532e3b6a48d29f9
size 8122
```

Environment:
- OS: Ubuntu 20.04
- Arch: x86_64
- No NVIDIA
- FFMPEG version:4.2.4-1ubuntu0.1

**Comment by leszko** [comment]
@oscar-davids do you maybe have any clue?

**Comment by oscar-davids** [comment]
-1 mean that there was no signature file or file size is zero, invalid signature. will recheck test.sh on my side.

**Comment by darkdarkdragon** [comment]
@leszko @yondonfu @oscar-davids this happens because I've put binary `test.phash` file that is used in this test into git-lfs.
So git-lfs should be properly initialised for the repo
```sh
git lfs install
git lfs pull
```

**Comment by oscar-davids** [comment]
Right, our mpeg-7 signature binary file couldn't be able to read as text like above(version... oid sha256:ad809c74a69f68a364c3b133d1f2cbf23fa04ea7d3fea9448532e3b6a48d29f9 ...size 8122)
cc @leszko @yondonfu 

@darkdarkdragon the signature file size for core/test.ts is 20k byte, less than core/test.ts. How about add the signature file as raw data?
