### ISSUE TITLE
integration common functions related to video profile.

### ISSUE THREAD

**Issue by oscar-davids** [livepeer/lpms#283]
A follow up to[ #276](https://github.com/livepeer/lpms/pull/276).

Below functions are used in both lpms and go-livepeer.
DefaultProfileName, EncoderProfileNameToValue, parseProfiles(JSON)
So we should move these someplace common, like ffmpeg/videoprofile.go, to avoid duplication.

**Comment by yondonfu** [comment]
For more context:

- As noted in [this comment](https://github.com/livepeer/lpms/pull/276/files#r764893675), the aforementioned helper functions are used in go-livepeer and LPMS so there is duplication
- The aforementioned helper functions can be found in go-livepeer [here](https://github.com/livepeer/go-livepeer/blob/f558a7052ba2e2ea86e7d8b52f69c6852c551100/common/util.go#L254)

If we move these functions into `ffmpeg/videoprofile.go` then they can be re-used in go-livepeer and in LPMS to reduce code duplication.
