### ISSUE TITLE
Transcoded segment timestamp incorrect

### ISSUE THREAD

**Issue by ericxtang** [livepeer/lpms#29]
Transcoder output don't have the right timestamp, therefore the playback is very choppy.

**Comment by ericxtang** [comment]
It turns out the choppiness is not from the timestamp.  My computer gets overloaded when running broadcasting AND transcoding at the same time, and that makes the encoder create choppy video.  

This is still a problem, just not the most immediate thing to fix.

**Comment by dob** [comment]
"that makes the encoder create choppy video"...

Does the encoder actually output "choppy video" that contains errors, or is
it just that you perceive it as choppy when consuming it live because your
computer is overloaded? If the former, that's troubling.

**Comment by ericxtang** [comment]
@dob sorry for not being clear - the encoder I'm referring to is for first-time encoding from raw pixels to digital video (OBS or FFMpeg).  As far as I can tell, the ffmpeg "transcoder" just changes the resolution for whatever video you pass in - so it'll output choppy videos if you pass in choppy videos.

**Comment by j0sh** [comment]
Doing some housekeeping, closing this since it seems to have been a local issue.
