### ISSUE TITLE
TestTranscoder_DetectionFreq failing in CI

### ISSUE THREAD

**Issue by yondonfu** [livepeer/lpms#301]
The `TestTranscoder_DetectionFreq` seems to be consistently failing in CI with the following error:

```
[swscaler @ 0x7fc0fd514040] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fc0fd514040] deprecated pixel format used, make sure you did set range correctly
[livepeer_dnn @ 0x7fc25dafdfc0] could not create DNN module for requested backend
[livepeer @ 0x7fc25c07b880] failed to initialize DNN backend
ERROR: transcoder.c:510] Invalid argument : Invalid argument
--- FAIL: TestTranscoder_DetectionFreq (2.72s)
    api_test.go:1459: DetectorInitializationError
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x744bd3]

goroutine 140 [running]:
testing.tRunner.func1.1(0x79e1c0, 0xa53fb0)
	/usr/local/go/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000103680)
	/usr/local/go/src/testing/testing.go:1075 +0x41a
panic(0x79e1c0, 0xa53fb0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/livepeer/lpms/ffmpeg.(*Transcoder).StopTranscoder(0x0)
	/go/src/github.com/livepeer/lpms/ffmpeg/ffmpeg.go:616 +0x33
panic(0x79e1c0, 0xa53fb0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/livepeer/lpms/ffmpeg.(*Transcoder).Transcode(0x0, 0xc000433c68, 0xc000180240, 0x2, 0x2, 0x0, 0x0, 0x0)
	/go/src/github.com/livepeer/lpms/ffmpeg/ffmpeg.go:312 +0x51
github.com/livepeer/lpms/ffmpeg.detectionFreq(0xc000103680, 0x0, 0x7fd726, 0x2)
	/go/src/github.com/livepeer/lpms/ffmpeg/api_test.go:1482 +0x42e
github.com/livepeer/lpms/ffmpeg.TestTranscoder_DetectionFreq(0xc000103680)
	/go/src/github.com/livepeer/lpms/ffmpeg/api_test.go:1493 +0x49
testing.tRunner(0xc000103680, 0x81fd98)
	/usr/local/go/src/testing/testing.go:1123 +0xef
```

Here is an example of a [failed build](https://app.circleci.com/pipelines/github/livepeer/lpms/363/workflows/9c3f456e-9d60-43c7-8a80-055352a191a7/jobs/811).

**Comment by yondonfu** [comment]
This test was enabled in https://github.com/livepeer/lpms/pull/289 - @JamesWanglf any thoughts?

**Comment by JamesWanglf** [comment]
To run this test function, we need to download [tasmodel.pb](https://github.com/livepeer/livepeer-ml/releases/download/v0.3/tasmodel.pb) first. I have added this [step](https://github.com/livepeer/lpms/blob/7437e4b92a575d856c419d4f29f6b57beba6e55f/install_ffmpeg.sh#L68) in install_ffmpeg.sh in LPMS.
But I found CircleCI is using install_ffmpeg.sh from go-livepeer. Because there is no `tasmodel.pb` file downloaded, so the error `could not create DNN module for requested backend` might be occurred.

**Comment by yondonfu** [comment]
@JamesWanglf Since the `install_ffmpeg.sh` script in go-livepeer is meant to install ffmpeg and its deps I think there is a reasonable argument for that script not to download a specific model. In order to fix CI, could we just add a download step for the `tasmodel.pb` file in CI before running tests to make sure that that specific model is accessible when tests run?

**Comment by JamesWanglf** [comment]
Yes, I fully agree with you. It must be added to the CI steps.
