### ISSUE TITLE
B gets some broken mpeg7 hash files when comparison of two hashes 

### ISSUE THREAD

**Issue by oscar-davids** [livepeer/lpms#338]
In fast verification, we run a comparison of MPEG-7 hashes from two T nodes. In most cases it's successful, but sometimes there are some failures. I guess this is about 5%.
When it failed, according to analyzing the hash pairs, these are couldn't read by our source code here  https://github.com/livepeer/lpms/blob/d82aa89e247702de2e1eed9a352c18fb4c459367/ffmpeg/extras.c#L204 and [here](https://github.com/livepeer/FFmpeg/blob/c0dcf5491814e0b0503180087d9e5e997f51b367/libavfilter/vf_signature.c#L667). I think these files are broken.

I think the file can be broken in the following two cases.
1. When downloading the hash file from T to B.
2. When transcoding in T,

In case 1, we check for the success of downloading, so I think this case is very rare.
Therefore, I think there is a high possibility that was broken during transcoding.

I looked at the lpms code for a day, but I couldn't find a clue. I think we need to experiment more specifically.
here is collected hash data. [failhashes.zip](https://github.com/livepeer/lpms/files/8928994/failhashes.zip)

**Comment by yondonfu** [comment]
Are both the phash files returned by 2 separate Ts "broken"? Or is only a single phash file returned by 1 of the Ts "broken"?

**Comment by yondonfu** [comment]
Fixed by https://github.com/livepeer/FFmpeg/pull/27
