### ISSUE TITLE
Transcoder produces corrupt frames

### ISSUE THREAD

**Issue by AlexKordic** [livepeer/lpms#367]
3rd segment:

frame 0: OK
frame 1: OK
![_0002](https://user-images.githubusercontent.com/3812017/214028414-8d0e0a3c-02be-4af1-be9a-907d4f6212cf.png)
frame 2: CORRUPT
![_0003](https://user-images.githubusercontent.com/3812017/214028445-1a850684-ce29-42f5-9e1c-bd27aed2022f.png)

**Comment by j0sh** [comment]
Not sure if this is an issue since its been a while since reporting and there has been some work on LPMS since then. If there are still issues with the transcoder then would help to have a sample to test against.
