### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by linuxaged** [livepeer/lpms#45]
get error when run `go run cmd/example/main.go`

    I1215 16:19:50.098904   37078 lpms.go:56] HTTP Server listening on :8000
    I1215 16:19:50.099032   37078 lpms.go:52] LPMS Server listening on :1935
    I1215 16:19:50.120190   37078 main.go:168] Got req: %!(EXTRA string=/stream/6427cb354ffbb854ee9f)
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x127ea40]

    goroutine 22 [running]:
    main.main.func7(0xc420122180, 0x132d98a, 0x1a, 0xc42004def8, 0x1)
        /Users/apple/workspace/lpms/cmd/example/main.go:170 +0xe0
    github.com/livepeer/lpms/vidplayer.(*VidPlayer).rtmpServerHandlePlay.func1(0xc42005ea80)
        /Users/apple/workspace/go/src/github.com/livepeer/lpms/vidplayer/player.go:58 +0xcd
    github.com/nareix/joy4/format/rtmp.(*Server).handleConn(0xc420074d80, 0xc42005ea80, 0x1, 0x1)
        /Users/apple/workspace/go/src/github.com/nareix/joy4/format/rtmp/rtmp.go:73 +0xc1
    github.com/nareix/joy4/format/rtmp.(*Server).ListenAndServe.func1(0xc420074d80, 0xc42005ea80)
        /Users/apple/workspace/go/src/github.com/nareix/joy4/format/rtmp/rtmp.go:118 +0x39
    created by github.com/nareix/joy4/format/rtmp.(*Server).ListenAndServe
        /Users/apple/workspace/go/src/github.com/nareix/joy4/format/rtmp/rtmp.go:117 +0x1b6
    exit status 2

macOS 10.12.6
go 1.9.2

**Comment by ericxtang** [comment]
Fixed https://github.com/livepeer/lpms/commit/8c81d54818802ed5f09c642a9a6334288e298680
