### ISSUE TITLE
ffmpeg.go:32] RTMP2HLS Transmux Return : File name too long

### ISSUE THREAD

**Issue by ya7ya** [livepeer/lpms#63]
Hey livepeer team,
I ran into this error while trying to broadcast to `livepeer`. Any Advice ?? 

cc @ericxtang 😄 

**go-livepeer version:** `0.1.14-unstable`
**livepeer command:** `./livepeer -bootnode -v 4 -offchain`
**ffmpeg version:** `3.1-static` from `static-ffmpeg` repo.

**ffmpeg command** `ffmpeg -i "Heat.1995.mp4" -framerate 30 -vcodec libx264 -tune zerolatency -b 1000k -acodec aac -ac 1 -b:a 96k -strict -2 -f flv "rtmp://localhost:1935/movie2"`

**OS:** Ubuntu 16.04 64bit

**output:**

```bash
Setting up bootnode
I0325 21:23:06.418290   32565 basic_network.go:457] 

Setting up protocol: /livepeer_video/0.0.1
I0325 21:23:06.418321   32565 livepeer.go:191] ***Livepeer is in off-chain mode***
I0325 21:23:06.418971   32565 lpms.go:59] HTTP Server listening on :8935
I0325 21:23:06.419046   32565 lpms.go:55] LPMS Server listening on :1935
I0325 21:23:06.602802   32565 basic_notifiee.go:62] Notifiee - ClosedStream: 1220e272e0beb8c0a247b74d3411755ccbf0091b71c133d59be6525c8bd25c7e2b05 - 122019c1a1f0d9fa2296dccb972e7478c5163415cd55722dcf0123553f397c45df7e
I0325 21:23:14.347583   32565 listener.go:32] RTMP server got upstream: rtmp://localhost:1935/movie2
I0325 21:23:14.424086   32565 mediaserver.go:166] Cannot automatically detect the video profile - setting it to {P720p30fps16x9 4000k 30 1280x720 16:9}
I0325 21:23:14.424194   32565 mediaserver.go:267] 

ManifestID: 1220e272e0beb8c0a247b74d3411755ccbf0091b71c133d59be6525c8bd25c7e2b05456832baaa3de8f0c8de6e30c3f0427ee3471eae2e0477c30d8477b3b0ed5387

I0325 21:23:14.424226   32565 mediaserver.go:268] 

hlsStrmID: 1220e272e0beb8c0a247b74d3411755ccbf0091b71c133d59be6525c8bd25c7e2b05456832baaa3de8f0c8de6e30c3f0427ee3471eae2e0477c30d8477b3b0ed5387P720p30fps16x9

I0325 21:23:14.424295   32565 lpms.go:99] Segment RTMP Req: rtmp://localhost:1935/stream/1220e272e0beb8c0a247b74d3411755ccbf0091b71c133d59be6525c8bd25c7e2b059491545e46f4a8faa2948850ba584757bd5a67f4c1e7dd15d084606ed46068f1RTMP
I0325 21:23:14.544019   32565 player.go:57] LPMS got RTMP request @ rtmp://localhost:1935/stream/1220e272e0beb8c0a247b74d3411755ccbf0091b71c133d59be6525c8bd25c7e2b059491545e46f4a8faa2948850ba584757bd5a67f4c1e7dd15d084606ed46068f1RTMP
Error writing header
I0325 21:23:14.793332   32565 ffmpeg.go:32] RTMP2HLS Transmux Return : File name too long
I0325 21:23:14.793363   32565 video_segmenter.go:239] Cleaning up video segments.....
E0325 21:23:14.793424   32565 lpms.go:138] Error segmenting stream: File name too long
I0325 21:23:14.810225   32565 basic_rtmp_videostream.go:42] RTMP stream got error: write tcp 127.0.0.1:1935->127.0.0.1:55292: write: connection reset by peer
I0325 21:23:50.213398   32565 livepeer.go:342] Exiting Livepeer: interrupt

```

**Comment by ericxtang** [comment]
Not sure if I've seen this bug before... @j0sh do you have any ideas?

**Comment by j0sh** [comment]
Strange, that's a new one for me too.

@ya7ya does it happen consistently, or only once? The latter might indicate an issue with the environment, while the former might be an unfortunate interaction with the generated filename and $something_else. Can't seem to trigger it here, even with the same filename.

**Comment by ya7ya** [comment]
@j0sh hey, it happens all the time, I think it might be my fault since you guys can't reproduce that. Are you guys using `ubuntu` ?? I suspect it might be a filename system issue.

**Comment by ericxtang** [comment]
Oh thanks for solving your own bug report @ya7ya!  Sounds like the solution is to have a concept of a tmp dir, or shorten the file name.  Are you ok with using the `/tmp` dir for the moment?  We'll figure out a good solution for this and put in a fix, but might not be able to get to it in the next few weeks.

**Comment by ya7ya** [comment]
@ericxtang Yeah, I'm good with tmp for now. the issue will arise if the .lpData is stored on an encrypted drive. so heads up 😄 for future ppl googling..
