### ISSUE TITLE
error when install lpms

### ISSUE THREAD

**Issue by bary321** [livepeer/lpms#79]
when i run command "go get github.com/livepeer/lpms"
i get a errror 
```
root@f06ed28f1cbf:/go# 
root@f06ed28f1cbf:/go# go get github.com/livepeer/lpms
package github.com/livepeer/lpms: no Go files in /go/src/github.com/livepeer/lpms
root@f06ed28f1cbf:/go# 
```
How do I solve this problem？
Is there any other way to get this program?

**Comment by j0sh** [comment]
Thanks for the report. The README was out of date and I've updated it -- https://github.com/livepeer/lpms/pull/78

Note that the "no Go files" message is just a somewhat confusing warning from golang. The LPMS code should be present on your computer at `/go/src/github.com/livepeer/lpms` .

To build the example program, do this:

```
cd /go/src/github.com/livepeer/lpms
<run install_ffmpeg.sh as needed, and ensure that libav* is visible to your PKG_CONFIG_PATH>
go build cmd/example/main.go
./example
```

**Comment by j0sh** [comment]
@bary321 Is this still an issue? If not, I'll close the ticket shortly.
