### ISSUE TITLE
http server sometimes fails to start, meaning that livepeer_cli is unusable

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/lpms#80]
The http server does not always start up when I start the node in --transcoder mode.

This means that the livepeer_cli is unable to connect to the livepeer media server :(

Running on Ubuntu 16.04. I have tried many things, like restarting the machine, using a different internet connection.

Here is a video which shows the behaviour: https://youtu.be/qSHv3M9B76c

**Comment by ericxtang** [comment]
@chrishobcroft does this issue go away if you are running as a broadcaster instead of a transcoder?

**Comment by chrishobcroft** [comment]
OK, so rigorous testing shows:

- When running in broadcaster mode, the http server consistently starts successfully

- When running in transcoder mode, the http server **does not** start consistently.

**Comment by dob** [comment]
Hey I know some of this is contained within the video at random points, but could you share the exact command you're using to start the transcoder?

I think the two lines that I see output on my own node when running this test, that you aren't seeing are:

```
I0529 15:52:08.118620   86916 mediaserver.go:95] Transcode Job Price: 1, Transcode Job Type: [{P240p30fps16x9 600k 30 426x240 16:9} {P360p30fps16x9 1200k 30 640x360 16:9}]
I0529 15:52:08.118726   86916 lpms.go:89] HTTP Server listening on http://127.0.0.1:8935
```

**Comment by j0sh** [comment]
A lot has changed for Streamflow and we haven't received other reports of this type of behavior in LPMS, so closing this issue for now. If something similar comes up then feel free to reopen this or create another ticket.
