### ISSUE TITLE
http api docs

### ISSUE THREAD

**Issue by blake41** [livepeer/lpms#86]
As far as I know these do not exist. I know I can ask for /manifestId as that is stated in the general getting started, but it would be cool to know what else is exposed, and/or have a place where people could request endpoints to be added.

One thing I thought might be fun to build is a way to see how many streams the livepeer media server was streaming at any given time. This is pretty low priority, but curious if the http interface could tell me this.

**Comment by j0sh** [comment]
Note that `/manifestID` is part of the goclient CLI API, not LPMS. The only HTTP endpoints LPMS exposes are for playback. LPMS serves the content itself (HLS manifests and mpegts segments), but there aren't any informational/diagnostic endpoints.

However, the CLI API itself is undocumented, and I agree that there are a lot of tools that can be built using it. Here's a ticket related to that: https://github.com/livepeer/go-livepeer/issues/553

**Comment by j0sh** [comment]
Closing this as the underlying issue of missing documentation is goclient-specific and captured in https://github.com/livepeer/go-livepeer/issues/553
