### ISSUE TITLE
CORS header

### ISSUE THREAD

**Issue by blake41** [livepeer/lpms#87]
Please add a CORS header so that a client can request the manifest ID

**Comment by j0sh** [comment]
Presumably you mean the CLI API, eg `/manifestID`? The `Access-Control-Allow-Origin` header is already set in several places in LPMS itself, but let me know if that's not the case.

**Comment by blake41** [comment]
Ahh, didn't realize that was calling the CLI API, yes you are correct

**Comment by j0sh** [comment]
I think this fix https://github.com/livepeer/go-livepeer/pull/557 would be a better alternative to adding CORS to the CLI API and exposing that. For @blake41 , it would eliminate the  `/manifestID` lookup step in the broadcast playback process. Target `/stream/current.m3u8` to get the stream associated with the currently active ManifestID.

**Comment by blake41** [comment]
oh wow that seems perfect!
/stream/current.m3u8 will serve me the current stream rather than having to request by manifest id?

**Comment by j0sh** [comment]
> stream/current.m3u8 will serve me the current stream rather than having to request by manifest id?

Yes, exactly.

**Comment by j0sh** [comment]
Resolved with the use of `current.m3u8`
